// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// predictSurv1
arma::vec predictSurv1(const double& t, const arma::mat& X, const arma::vec& betaX, const double& b, const double& ln_p);
RcppExport SEXP _stdmest_predictSurv1(SEXP tSEXP, SEXP XSEXP, SEXP betaXSEXP, SEXP bSEXP, SEXP ln_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type t(tSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type betaX(betaXSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double& >::type ln_p(ln_pSEXP);
    rcpp_result_gen = Rcpp::wrap(predictSurv1(t, X, betaX, b, ln_p));
    return rcpp_result_gen;
END_RCPP
}
// predictMeanSurv1
arma::mat predictMeanSurv1(const arma::vec& t, const arma::mat& X, const arma::mat& betaX, const arma::vec& b, const arma::vec& ln_p);
RcppExport SEXP _stdmest_predictMeanSurv1(SEXP tSEXP, SEXP XSEXP, SEXP betaXSEXP, SEXP bSEXP, SEXP ln_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type t(tSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type betaX(betaXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ln_p(ln_pSEXP);
    rcpp_result_gen = Rcpp::wrap(predictMeanSurv1(t, X, betaX, b, ln_p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stdmest_predictSurv1", (DL_FUNC) &_stdmest_predictSurv1, 5},
    {"_stdmest_predictMeanSurv1", (DL_FUNC) &_stdmest_predictMeanSurv1, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_stdmest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
