# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predictSurv1 <- function(t, X, betaX, b, ln_p) {
    .Call(`_stdmest_predictSurv1`, t, X, betaX, b, ln_p)
}

predictMeanSurv1 <- function(t, X, betaX, b, ln_p) {
    .Call(`_stdmest_predictMeanSurv1`, t, X, betaX, b, ln_p)
}

